/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library.management;

import java.sql.SQLException;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author EliteBook
 */
public class clerkform extends javax.swing.JFrame {
   library lib;
    List <loan>loans;
    int id;
    
 public clerkform(library lib,List <loan> loans,int id) {
   
     this.lib=lib;
        this.loans=loans;
        this.id=id;
     
        initComponents();
    }
    
    
    public clerkform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        borrower = new javax.swing.JButton();
        issueloan = new javax.swing.JButton();
        checkin = new javax.swing.JButton();
        update = new javax.swing.JButton();
        updatefine = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        updateborrower = new javax.swing.JButton();
        printlib = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        jLabel1.setText("Clerk Portal");

        borrower.setText("Borrower's tasks");
        borrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowerActionPerformed(evt);
            }
        });

        issueloan.setText("Issue loan");
        issueloan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueloanActionPerformed(evt);
            }
        });

        checkin.setText("check in");
        checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinActionPerformed(evt);
            }
        });

        update.setText("update Book");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        updatefine.setText("update fine");
        updatefine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatefineActionPerformed(evt);
            }
        });

        signup.setText("Sign up User");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        updateborrower.setText("Update user");
        updateborrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateborrowerActionPerformed(evt);
            }
        });

        printlib.setText("Print library");
        printlib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printlibActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrower)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(update)
                                        .addGap(97, 97, 97))
                                    .addComponent(updatefine, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(issueloan)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(checkin)))
                                .addGap(142, 142, 142)))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(signup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printlib, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(updateborrower, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(borrower)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(issueloan)
                .addGap(11, 11, 11)
                .addComponent(checkin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(updatefine)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signup)
                    .addComponent(updateborrower)
                    .addComponent(printlib))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinActionPerformed
 
        user u=lib.getuserbyid(id);
        Scanner myscan=new Scanner(System.in);
        System.out.println("Enter Book id");
        int bookid=myscan.nextInt();
        System.out.println("Enter loan id");
        int loanid=myscan.nextInt();
        
       try {
           u.checkin(bookid, loanid);
           
           
           
// TODO add your handling code here:
       } catch (SQLException ex) {
           Logger.getLogger(clerkform.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_checkinActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        user u=lib.getuserbyid(id);
       try {
           u.updatebook();
       } catch (SQLException ex) {
           Logger.getLogger(clerkform.class.getName()).log(Level.SEVERE, null, ex);
       }
        
       
       
    }//GEN-LAST:event_updateActionPerformed

    private void issueloanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueloanActionPerformed

         user u=lib.getuserbyid(id);
       try {
           u.issueloan();
           
           
           
           // TODO add your handling code here:
       } catch (Exception ex) {
           Logger.getLogger(clerkform.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_issueloanActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
       
        
         user u=lib.getuserbyid(id);
       try {
           u.Signupuser();
           
           
// TODO add your handling code here:
       } catch (SQLException ex) {
           Logger.getLogger(clerkform.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_signupActionPerformed

    private void borrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowerActionPerformed
        
        borrowerform b=new  borrowerform(lib,loans,id);
        b.setVisible(true);
        dispose();
        

// TODO add your handling code here:
    }//GEN-LAST:event_borrowerActionPerformed

    private void updatefineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatefineActionPerformed
        user u=lib.getuserbyid(id);
       try {
           u.updatefinestatus();
           
// TODO add your handling code here:
       } catch (SQLException ex) {
           Logger.getLogger(clerkform.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_updatefineActionPerformed

    private void updateborrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateborrowerActionPerformed
       user u=lib.getuserbyid(id);
       try {
           u.updateuserinfo();
           
// TODO add your handling code here:
       } catch (SQLException ex) {
           Logger.getLogger(clerkform.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_updateborrowerActionPerformed

    private void printlibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printlibActionPerformed
       
     lib.printlibrary();
// TODO add your handling code here:
    }//GEN-LAST:event_printlibActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clerkform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clerkform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clerkform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clerkform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clerkform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrower;
    private javax.swing.JButton checkin;
    private javax.swing.JButton issueloan;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton printlib;
    private javax.swing.JButton signup;
    private javax.swing.JButton update;
    private javax.swing.JButton updateborrower;
    private javax.swing.JButton updatefine;
    // End of variables declaration//GEN-END:variables
}
